SHOTS = 1024
MAX_CREDITS = 3
# CONSIDERED_REMOTE_BACKENDS = ['ibmqx2', 'ibmq_5_tenerife', 'ibmqx5']
CONSIDERED_REMOTE_BACKENDS = ['ibmqx4']
ITERATIONS_NUMBER = 1000000
CSV_SEPARATOR = ';'
JOBS_DOWNLOAD_LIMIT = 200
