#SHOTS = 1024
SHOTS = 8192
MAX_CREDITS = 3
# CONSIDERED_REMOTE_BACKENDS = ['ibmqx2']
CONSIDERED_REMOTE_BACKENDS = ['ibmqx4']
ITERATIONS_NUMBER = 1000

# Job gatherer
CSV_SEPARATOR = ';'
JOBS_DOWNLOAD_LIMIT = 1500
MAX_JOBS_SINGLE_DOWNLOAD_NUM = 100
JOBS_REPORT_HEADER = 'ID;Backend;Circuit;Date;Results\n'
JOBS_FILE_NAME = "jobs_report.csv"

# Scripts working constants
