---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                      fig.width=12, fig.height=7)
source('analysis_methods.R')
```

```{r}
data = str_c ('jobs_report (',1:2,').csv')  %>% lapply(read_csv) %>% bind_rows %>% distinct
data %>% print_basic_info
data1 = str_c ('m_jobs_report (',1:2,').csv')  %>% lapply(read_csv) %>% bind_rows %>% distinct
data2 = data %>% process_calibration()
```

# 2 QUBITS


## CHSH test

```{r}
chsh = bind_rows(
  raw = data %>% chsh_test(message = 'No mitigation:'),
  mitigated = data1 %>% chsh_test(message = 'After mitigation:'),
  calibrated = data2 %>% chsh_test(message = 'Manual calibration:'),
  .id = 'mit')
chsh %<>%
  mutate(mit = factor(mit,
                      levels = c('raw', 'mitigated', 'calibrated'))) %>%
  group_by(mit)
```


## Sanity check


```{r}
sc_signaling = chsh %>% process_sc %>% process_signaling

sc_signaling %>%
  plot_signaling(facet_y = quo(mit), facet_x = quo(state)) %>%
    plyr::l_ply(print)
```



## CHSH



```{r}
chsh %<>% process_chsh(barrier = FALSE)

chsh %>% agg_data %>% bell_fit_plot('CHSH')

chsh_signaling = chsh %>% process_signaling

plyr::l_ply(chsh_signaling$qubit %>% unique, function(i){
  
  chsh_signaling %>%
  filter(qubit == i) %>%
  plot_signaling(
    x = quo(theta),
    facet_x = quo(my_base),
    facet_y = quo(mit)
    ) %>%
    
    plyr::l_ply(function(p){
      print(
        p+pi_axis()+ggtitle(str_c('Nr of qubit: ', i))
        )})
  
})
```


# 3 QUBITS


## Mermin test

```{r}
mermin = bind_rows(
  raw = data %>% mermin_test(message = 'No mitigation:'),
  mitigated = data1 %>% mermin_test(message = 'After mitigation:'),
  calibrated = data2 %>% mermin_test(message = 'Manual calibration:'),
  .id = 'mit')
mermin %<>%
  mutate(mit = factor(mit,
                      levels = c('raw', 'mitigated', 'calibrated'))) %>%
  group_by(mit)
```


## Sanity check


```{r}
sc_signaling = mermin %>% process_sc %>% process_signaling

sc_signaling %>%
  plot_signaling(facet_y = quo(mit), facet_x = quo(state)) %>%
    plyr::l_ply(print)
```



## Mermin



```{r}
mermin %<>% process_mermin(barrier = FALSE, parameter = TRUE)

mermin %>% agg_data %>% bell_fit_plot('Mermin')

mermin_signaling = mermin %>% process_signaling

plyr::l_ply(mermin_signaling$qubit %>% unique, function(i){
  
  mermin_signaling %>%
  filter(qubit == i) %>%
  plot_signaling(
    x = quo(theta),
    facet_x = quo(my_base),
    facet_y = quo(mit)
    ) %>%
    
    plyr::l_ply(function(p){
      print(
        p+pi_axis()+ggtitle(str_c('Nr of qubit: ', i))
        )})
  
})
```

