---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                      fig.width=12, fig.height=7)
source('analysis_methods.R')
```

```{r}
data = read_csv('C:/Users/ala/Downloads/no_signaling (1).csv')
data %>% print_basic_info

data %<>% chsh_test
```


## Mermin

```{r}
mermin = data %>% process_mermin(barrier = TRUE)

mermin %>% agg_data(print_kable = TRUE)

mermin_signaling = mermin %>% process_signaling
mermin_signaling %>%
  plot_signaling(facet_y = quo(barrier)) %>% plyr::l_ply(print)
```


## CHSH

```{r}
chsh = data %>% process_chsh(barrier = TRUE)

chsh %>% agg_data %>% bell_fit_plot('CHSH')

chsh_signaling = chsh %>% process_signaling

plyr::l_ply(chsh_signaling$qubit %>% unique, function(i){
  
  chsh_signaling %>%
  filter(qubit == i) %>%
  plot_signaling(
    x = quo(theta),
    facet_x = quo(my_base),
    facet_y = quo(barrier)) %>%
    
    plyr::l_ply(function(p){
      print(
        p+pi_axis()+ggtitle(str_c('Nr of qubit: ', i))
        )})
  
})
```


## Sanity check

```{r}
sc = data %>% process_sc

sc_signaling = sc %>% process_signaling

for(n in sc$n_qubits %>% unique){
  print(str_c('number of qubits: ',n))
  sc_signaling %>% filter(n_qubits == n) %>%
  plot_signaling(facet_y = quo(barrier), facet_x = quo(state)) %>%
    plyr::l_ply(print)
}

```